### ISSUE TITLE
After configuration, click on ask chatgpt and there is no response

### ISSUE THREAD

**Issue by MrYangyt** [robusta-dev/kubernetes-chatgpt-bot#24]
After configuration, click on ask chatgpt and there is no response
<img width="737" alt="image" src="https://github.com/robusta-dev/kubernetes-chatgpt-bot/assets/32567408/6b286877-f8fc-49fd-bc44-4cd10fb0b3ee">

**Comment by aantn** [comment]
Are there any errors in the robusta-runner pod logs?

**Comment by MrYangyt** [comment]
<img width="1513" alt="image" src="https://github.com/robusta-dev/kubernetes-chatgpt-bot/assets/32567408/22b03023-7dd4-4eb1-b216-258165e857d8">
Is this my Prometheus not properly configured? I am using my own pre-existing Prometheus. Do I need to make any special configurations

**Comment by arikalon1** [comment]
Hi @MrYangyt 

In order to use Slack buttons, you must verify that `disableCloudRouting` is set to `false` in the `generated_values.yaml` file (this is the default)
Is that the case in your cluster?

Regarding the error, it indicates Robusta can't automatically detect your Prometheus service.
You need to specify it manually in the `geneated_values.yaml` file, like this:
```
globalConfig:
  prometheus_url: http://my-prometheus-cluster-dns....
```

**Comment by MrYangyt** [comment]
Got it, thank you. I'll try again

**Comment by aantn** [comment]
Closing, but please re-open if the issue continues.
